### ISSUE TITLE
Publisher multi-stream 

### ISSUE THREAD

**Issue by OrlandoCo** [ionorg/ion#100]
## Summary

In a one to many/many to many scenario, if a single user of the conference can't handle the bitrate, it would affect all the users in the conference lowering the quality of the video.

If the puplisher uploads at least 2 video quality at the same time [HD,QVGA...] , the SFU router can switch between these qualities, instead lowering the bitrate of publisher.

## Additional context

Reference:
[opentok](https://support.tokbox.com/hc/en-us/articles/360029733831-TokBox-Scalable-Video-Simulcast-FAQ)

**Comment by cloudwebrtc** [comment]
@OrlandoCo @Sean-Der We can support `simulcast/SVC` later so that a single publish stream can contain multiple bit rates and resolutions. When subscribing, you can subscribe to the corresponding stream by using parameters like `T2, S2 | T0, S1`.
related issue https://github.com/pion/webrtc/issues/1016

**Comment by akilude** [comment]
WIth simulcast/SVC, It would also be nice to have voice detection in the server so that we know when we are on "stage" when there are lots of users in the call so that we can send only the required substreams (s0-s2) , Please see https://webrtchacks.com/suspending-simulcast-streams/

**Comment by cloudwebrtc** [comment]
@akilude Super good idea.

**Comment by tarrencev** [comment]
Looks like this will hopefully be supported soon! https://github.com/pion/webrtc/pull/1200
