### ISSUE TITLE
sfu panic when a second user joins via the demo app

### ISSUE THREAD

**Issue by alexferl** [ionorg/ion#111]
### Your environment.
  - Version: e936c2a
  - Browser: Chrome 80.0.3987.149 macOS
  - Other Information:

```
sfu_1    | 2020-04-07 02:18:30.871 INF rtc.GetOrNewRouter id=02121ce9-7ebb-46fa-9af9-96b321bf03d5#LNPHGT
sfu_1    | 2020-04-07 02:18:30.871 INF rtc.GetRouter id=02121ce9-7ebb-46fa-9af9-96b321bf03d5#LNPHGT
sfu_1    | 2020-04-07 02:18:30.871 INF rtc.AddRouter id=02121ce9-7ebb-46fa-9af9-96b321bf03d5#LNPHGT
sfu_1    | 2020-04-07 02:18:30.871 INF NewRouter id=02121ce9-7ebb-46fa-9af9-96b321bf03d5#LNPHGT
sfu_1    | 2020-04-07 02:18:30.872 INF subscribe tracks=map[eI5U01z2tJlCU1ikLuNVeAFZMp18njodeUMJ 066a306c-c5f5-4b93
-ad09-766dd9383657:[map[id:066a306c-c5f5-4b93-ad09-766dd9383657 pt:111 ssrc:4.273608241e+09 type:audio]] eI5U01z2tJ
lCU1ikLuNVeAFZMp18njodeUMJ e02b1007-9974-4d61-859b-b4d52a39e2ed:[map[id:e02b1007-9974-4d61-859b-b4d52a39e2ed pt:96 
ssrc:1.143603203e+09 type:video]]]
sfu_1    | panic: interface conversion: interface {} is nil, not string
sfu_1    | 
sfu_1    | goroutine 32 [running]:
sfu_1    | github.com/pion/ion/pkg/node/sfu.subscribe(0xc0003b92f0, 0x9, 0xf2a2c2)
sfu_1    |      /go/src/github.com/pion/ion/pkg/node/sfu/internal.go:205 +0x1630
sfu_1    | github.com/pion/ion/pkg/node/sfu.handleRequest.func1(0xc0003b92c0, 0xc0003b93e0, 0xc0003b9410)
sfu_1    |      /go/src/github.com/pion/ion/pkg/node/sfu/internal.go:35 +0x2d8
sfu_1    | github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleRequest(0xc000173e60, 0xc0003b92c0, 0xc0003ccbc0, 0x14, 0xc0003ccbe0, 0x19)
sfu_1    |      /go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:150 +0x1d4
sfu_1    | github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleMessage(0xc000173e60, 0xc0003ce000, 0x16db, 0x16db, 0xc0003ccbc0, 0x14, 0xc0003ccbe0, 0x19)
sfu_1    |      /go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:105 +0x156
sfu_1    | github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).onRequest(0xc000173e60, 0xc0003cac30)
sfu_1    |      /go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:96 +0x198
sfu_1    | github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0000b7b80, 0xc00016a240)
sfu_1    |      /go/pkg/mod/github.com/nats-io/nats.go@v1.9.1/nats.go:2147 +0x330
sfu_1    | created by github.com/nats-io/nats%2ego.(*Conn).subscribe
```

Seems like it's panicking [here](https://github.com/pion/ion/blob/e936c2a38cbc76caca808a2b46bd348d61785494/pkg/node/sfu/internal.go#L205) because the `msg` didn't contain a `codec` in the tracks map, line with timestamp `2020-04-07 02:18:30.872` in the stacktrace.

### What did you do?
1. `docker-compose up` on a GCP compute engine node. 
2. Accessed ion at https://mydomain:8080 created a room 'test' with a display name.
3. From another tab (or incognito mode) accessed ion at https://mydomain:8080 joined room 'test' with a different display name.

### What did you expect?
Seeing both users' video tracks.

### What happened?
sfu crashed.

**Comment by adwpc** [comment]
Maybe this sdk is old version. do't have the `codec`, you can try without docker 
We should make a new web docker which contains new sdk
@Sean-Der 
Maybe we need a script to build docker and upload?

**Comment by sashaaro** [comment]
you can try check  https://github.com/pion/ion/pull/118 and execute `docker-compose up` there. it will build images locally if you will not run `docker-compose pull` explicitly before. By the way existed images work well for me.

**Comment by alexferl** [comment]
Pulling latest and doing `docker-compose up` to build my own images and it doesn't crash anymore but users get disconnected as soon as a second one joins.

**Comment by adwpc** [comment]
I got some error when building web docker  by running `docker-compose up`

Found bindings for the following environments:
  - OS X 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/usr/src/ion/demo/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/usr/src/ion/demo/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/usr/src/ion/demo/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/usr/src/ion/demo/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at getDefaultSassImpl (/usr/src/ion/demo/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/usr/src/ion/demo/node_modules/sass-loader/dist/index.js:80:29)
 @ ./node_modules/antd/es/avatar/style/index.css 2:14-109 21:1-42:3 22:19-114
 @ ./node_modules/antd/es/avatar/style/css.js
 @ ./src/videoview/LocalVideoView.jsx
 @ ./src/videoview/index.jsx
 @ ./src/Conference.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ion-js-demo@0.0.1 build: `webpack --mode=production --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ion-js-demo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T08_44_51_452Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache --update nodejs npm   && mkdir -p /app/demo   && npm install   && cd demo    && npm install   && npm run build   && mv dist /app/demo   && rm -rf /usr/src/ion /root/.npm /tmp/*   && apk del --no-cache nodejs npm' returned a non-zero code: 2

**Comment by Sean-Der** [comment]
@adwpc I am not sure, but can you try

* Deleting all `node_modules` directories in the project, if you installed before on your mac it may be building binaries that are failing in the container.
* `docker-compose down && docker container prune -f && docker image prune -af` this will clean out all unused containers/images and will force a redownload the next time

**Comment by adwpc** [comment]
I think this issue is fixed.
Thank you all!
