### ISSUE TITLE
Go CLI

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#227]
Any chance or anyone working on a golang CLI for all the server elements ?

I would like to be able to easily test out using ion as s kappa Architecture.

And also to configure users and user groups etc.

**Comment by tarrencev** [comment]
The closest thing we have right now is https://github.com/pion/ion-load-tool. I think @jbrady42 was planning to pull out the client as an ion-go-sdk. I think a cli would be awesome though. If that is something you are interested in working on, we'd welcome the contribution!

**Comment by joe-getcouragenow** [comment]
sorry all but no progress on this.

I actually want to use the CLI concept also as a client embedded layer for Web, Desktop and Mobile.
This would allow ion to work with flutter, React, GIo and other GUI frameworks.

SO you can run it as a CLI OR embed it into the GUI Layer. SO easy to test and play as a CLI before its gets hidden into a GUI layer.

There is a fair bit of merit in this and i have noticed others dong this by cross compiling golang for Web  using WASM and tinygo) and golang compile as a shared library using standard golang ( not gomobile) for mobiles.

BUT i think the React or JS people woudl not like it and i dont blame them as its just another layer in their way.

Anyway its an idea i am putting out there.
I am working on it anyway...


---

Also i dont think its possible with the way things are setup for ion. The NatsProto for example inherits from NATS, and so that wont cross compile to WASM :)

**Comment by leewardbound** [comment]
Hey there, it's not exactly what you're asking about, but check out https://github.com/pion/ion-examples --
I needed some CLI tools too, like `join-from-disk`, so i started this repository for connection examples to live.

Using these examples, I'm able to compile a distributable binary for `join-from-disk` (i haven't succeeded at anything crossplatform yet).

I can then run `join-from-disk -e {ion endpoint} -v {video file} -r {room} -u {username}` -- Is this kind of like what you wanted to accomplish?

I use this in `ion-e2e-tests` to verify the video is publishing!

These are all designed for `v0.4.6`, using the biz websocket API. Please note that for v0.5, we're splitting `ion-SFU` into a dedicated project.

The new `ion-sfu` will have a better API (JSON-RPC) for interacting directly with it, so you don't need NatsProto to write a client anymore; I'll make new CLI tools for `ion-SFU` at that time as well.

**Comment by joe-getcouragenow** [comment]
Ok yeah i see your point. Its a good way to test the ion Server from outside. 
Definitely worth it for me and others to test things

Well done since you are new to golang.

I still think a client layer designed to be cross compiled for web, desktop and mobile would be useful for many reasons to the project. Its bad to add another layer, and the way the client code calls into that layer can be hard to get right. I find Proto can always work.

Here is an example of this.
https://maori.geek.nz/a-web-app-using-bazel-golang-wasm-and-proto-c020914f4341
https://github.com/grahamjenson/bazel-golang-wasm-proto


This one is simpler, but uses the proto's also and produces a WASM that uses GRPC
https://github.com/ctessum/cityaq

**Comment by adwpc** [comment]
grpc version will come.
