### ISSUE TITLE
How does SFU expose the portrange of webrtc portrange in the k8s container

### ISSUE THREAD

**Issue by ainilili** [ionorg/ion#300]
As mentioned above, K8S does not seem to support exposing a port range, so SFU running in K8S containers cannot expose udp port range. Is there a corresponding solution?

**Comment by leewardbound** [comment]
Hi, the SFU container has `hostNetwork: true`, so it's able to expose UDP ports on the host machine. I chose to do this instead of assigning static ports, because it's not possible to expose a whole range in k8s so we'd be exposing ~200+ ports 1-by-1 (really should be raised to ~10k+), and both scenarios share the same primary drawback (a limit of 1 SFU per host node).

**Comment by ainilili** [comment]
I see, thanks!
