### ISSUE TITLE
Webview on desktop

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#34]
Run on desktop using a webview.

Does anyone know if we view has access to the audio and video camera ?

**Comment by adwpc** [comment]
the webview access may be the same as the desktop

**Comment by winwisely99** [comment]
SO on Desktop, Webview does or DOES NOT have access to the camera and mic ?

**Comment by cloudwebrtc** [comment]
Maybe using `Flutter Web` + `Electron` is another possible solution.

**Comment by winwisely99** [comment]
There is a great Webview that golang can use and cpp can use without all the Electron heaviness !

https://github.com/zserge/webview/tree/webview-x

From the Go-flutter code we would just need to open a Window that uses this and load the Flutter Web into it.

Do you want to try ?

**Comment by cloudwebrtc** [comment]
@winwisely99 Yes i want to try it out, is it possible to call webrtc api completely

**Comment by winwisely99** [comment]
As per discussion the best approach for now seems to be:

https://github.com/asticode/go-astilectron

A Make file ( or other ) using this approach here:
https://github.com/pion/ion/tree/master/sdk/flutter/example

**Comment by winwisely99** [comment]
I think this should be brought forward because it is important we know this works ASAP.

**Comment by winwisely99** [comment]
But what about Notifications and Deeplinking ?
- From Golang its pretty easy to do both, but need to make sure it

But what about Dialogs ? Might suck on Web. Lets see.

**Comment by cloudwebrtc** [comment]
> But what about Notifications and Deeplinking ?
> 
> * From Golang its pretty easy to do both, but need to make sure it
> 
> But what about Dialogs ? Might suck on Web. Lets see.

I think this example is only used to show running `Flutter Web app` based on [go-astilectron](https://github.com/asticode/go-astilectron) and package it into a Desktop App
Golang interaction with Flutter Web (JS) is another question because ION-based clients do not need to interact with golang on the client-side, you can refer to
https://github.com/asticode/go-astilectron-demo/blob/master/message.go#L18

**Comment by joe-getcouragenow** [comment]
Ok thanks @cloudwebrtc, i understand.

I think i have it worked out for Desktop Notifications:
See https://github.com/getcouragenow/packages/issues/34

**Comment by joe-getcouragenow** [comment]
SO summary is that ASTI Electron is unsuitable because of how it works.
It unpacks the Electron Framework files at install time ! SO you cant sign it. Its really a hack design IMHO.

The way to fix it is to embed those Framework files into the Desktop at compile time !
- then the ASTI golang code should still work call it
- then hover bundler will include the Electron Framework files when it packages things
