### ISSUE TITLE
I need android native sdk. Please help me

### ISSUE THREAD

**Issue by tuanha1305** [ionorg/ion#384]
I need android native sdk or help me to convert dart file to java.
Please help me

**Comment by ducanh3005** [comment]
+1 for native SDK ( for performance)
but you can read about Methodchannel

**Comment by ncs-ncs-scn-scn** [comment]
I need ios too

**Comment by leewardbound** [comment]
Hi thanks for your interest and welcome to ion! :+1: 

Currently there is no native IOS or Java SDK! But you can write an `ion` API client in any language that supports websockets and webrtc, pretty easily!

The `0.4.6` ion API is built with `go-protoo` but it's basically just a websocket sending 6 messages: `join`, `publish`, `subscribe`, `unsubscribe`, `unpublish`, and `leave`; you also need to watch for any `stream-add` and `stream-remove` events (when a peer sees a `stream-add`, they should fire a `subscribe` etc)

Please note that `0.5` will be a major release of `ion`, including a new SFU (`ion-sfu` has been moved to a totally standalone project, which `ion` imports) and the new `ion-sfu` has a `json-rpc` API which should be easier to integrate with; you can evaluate `ion-sfu` right now because it might already be a better candidate for you. The broader `ion` project will still have the `protoo` API and the same the goal of building a multi-datacenter conferencing suite based on many peered instances of `ion-sfu`.

Finally, it seems like there's a lot of you in Hanoi interested in this! Feel free to drop into #pion on the Go Gophers Slack if you want to discuss this (link in wiki, we use the golang room for ion stuff even though the Android and iOS SDK projects aren't `golang`). If you build a native Android or iOS client, the community would love to know about it!

**Comment by tuanha1305** [comment]
Thanks for awesome project! I will try base on ion flutter flow code. Hopefully I can make it
